// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uloqruecjcgupkrvmazd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsb3FydWVjamNndXBrcnZtYXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI1MjgxNTIsImV4cCI6MjA5ODEwNDE1Mn0.HEcFyYu3CIRjlxDGsnLOTj5_EbsKOVuSYCHRg-jhkvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});